### ISSUE TITLE
Was bezweckt die Extension

### ISSUE THREAD

**Issue by Benjamin-Scherf** [Craffft/accountmail-bundle#1]
Hallo, 

ich hoffe ich habe nichts überlesen. Unter den Projektdetails steht leider nur "Adds a accountmail frontend module for Contao OpenSource CMS". Könnten Sie bitte kurz beschreiben was diese Extension genau macht. Ich suche nach einer Extension mit der sich Frontendmitglieder gegenseitig Messages schreiben können. 

Vielen Dank

**Comment by iCodr8** [comment]
Die Erweiterung ermöglicht es einem Benutzer automatisiert die Zugangsdaten aus dem Backend heraus zuzusenden. Wenn ich einen neuen Benutzer (BE) oder ein neues Mitglied (FE) anlege, so bekommt dieser eine E-Mail mit den Zugangsdaten.

**Comment by Benjamin-Scherf** [comment]
Vielen Dank für die schnelle Antwort.
